import EditorialPage, {
  Rule,
  SectionTitle,
  P,
  GoldList,
} from '../../components/ui/EditorialPage.jsx'

const FACTS = [
  ['Established', '1997'],
  ['Authority', 'Florida Statute Chapter 163, Part III'],
  ['District', 'Entire incorporated town'],
  ['Meetings', 'Third Thursday, 6:30 p.m., Town Hall'],
  ['Financing', 'Tax Increment Financing (TIF)'],
  ['CRA Term', 'Limited to 30 years under Florida law'],
]

const RESOURCES = [
  {
    label: 'CRA Official Website',
    type: 'external',
    href: 'https://eatonvillecra.org',
  },
  {
    label: 'CRA Meeting Agendas — Municode',
    type: 'external',
    href: 'https://eatonville-fl.municodemeetings.com/',
  },
]

export default function CRA() {
  return (
    <EditorialPage
      eyebrow="Government"
      headline="Community Redevelopment Agency"
      subhead="Investing in Eatonville’s future without forgetting its past"
      factsLabel="Eatonville CRA"
      facts={FACTS}
      resources={RESOURCES}
    >
      <SectionTitle>What a CRA Is</SectionTitle>
      <P>
        A Community Redevelopment Agency is a tool authorized under Florida law
        — specifically Chapter 163, Part III of the Florida Statutes — that
        allows a municipality to direct increases in property tax revenue back
        into a defined redevelopment area. The mechanism is called Tax
        Increment Financing, or TIF: property values are assessed at a base
        year when the CRA is created, and any tax revenue generated by
        increases above that baseline is deposited into a dedicated trust fund.
        That fund can only be spent within the CRA district, on projects
        defined in a Community Redevelopment Plan. In plain terms: as
        Eatonville grows and property values rise, a portion of that growth
        comes back to Eatonville — to invest in infrastructure, economic
        development, housing, and community improvements.
      </P>

      <Rule />

      <SectionTitle>Eatonville’s CRA</SectionTitle>
      <P>
        The Town of Eatonville Community Redevelopment Agency was established
        in 1997. Its boundaries are coterminous with the incorporated town
        limits — meaning the entire town is the redevelopment area. The CRA’s
        stated mission is to create a thriving and economically robust
        commercial corridor with an emphasis on preserving the town’s historic
        character and charm, where residents and visitors can live, work, play,
        and grow. The CRA meets on the third Thursday of each month at 6:30
        p.m. at Town Hall, 307 E. Kennedy Blvd.
      </P>

      <Rule />

      <SectionTitle>What the CRA Should Be Doing for Eatonville</SectionTitle>
      <P>
        Eatonville’s CRA sits at one of the most consequential moments in the
        town’s history. Development pressure from the Orlando metropolitan area
        is real. The Hungerford School property — 100 acres that make up
        roughly 15% of the entire town — is a live question about the town’s
        future. Historic buildings along Kennedy Boulevard need investment. The
        town’s infrastructure requires modernization. A well-functioning CRA is
        one of the most powerful tools a small municipality has to shape its
        own future.
      </P>
      <GoldList
        items={[
          'Invest in Kennedy Boulevard as a historic and commercial corridor that reflects the town’s identity',
          'Support affordable housing so that the people who built this community can remain in it',
          'Preserve and activate historic assets — Club Eaton, the Hungerford property, the Historic District — as cultural and economic anchors',
          'Attract businesses and investment that serve existing residents, not displace them',
          'Fund infrastructure improvements that have long been deferred',
        ]}
      />

      <Rule />

      <SectionTitle>Accountability</SectionTitle>
      <P>
        The CRA is accountable to the residents of Eatonville. Its meetings are
        public. Its finances are public record. Residents are encouraged to
        attend, ask questions, and hold the board to the town’s best interests.
      </P>
    </EditorialPage>
  )
}
